#pragma once
#include "Room.h"
#include <vector>

using namespace std;

enum CARD
{
	CARDS_01_CLUBS = 1,
	CARDS_02_CLUBS,
	CARDS_03_CLUBS,
	CARDS_04_CLUBS,
	CARDS_05_CLUBS,
	CARDS_06_CLUBS,
	CARDS_07_CLUBS,
	CARDS_08_CLUBS,
	CARDS_09_CLUBS,
	CARDS_10_CLUBS,
	CARDS_11_CLUBS,
	CARDS_12_CLUBS,
	CARDS_13_CLUBS,
	CARDS_14_DIAMONDS,
	CARDS_15_DIAMONDS,
	CARDS_16_DIAMONDS,
	CARDS_17_DIAMONDS,
	CARDS_18_DIAMONDS,
	CARDS_19_DIAMONDS,
	CARDS_20_DIAMONDS,
	CARDS_21_DIAMONDS,
	CARDS_22_DIAMONDS,
	CARDS_23_DIAMONDS,
	CARDS_24_DIAMONDS,
	CARDS_25_DIAMONDS,
	CARDS_26_DIAMONDS,
	CARDS_27_HEARTS,
	CARDS_28_HEARTS,
	CARDS_29_HEARTS,
	CARDS_30_HEARTS,
	CARDS_31_HEARTS,
	CARDS_32_HEARTS,
	CARDS_33_HEARTS,
	CARDS_34_HEARTS,
	CARDS_35_HEARTS,
	CARDS_36_HEARTS,
	CARDS_37_HEARTS,
	CARDS_38_HEARTS,
	CARDS_39_HEARTS,
	CARDS_40_SPADES,
	CARDS_41_SPADES,
	CARDS_42_SPADES,
	CARDS_43_SPADES,
	CARDS_44_SPADES,
	CARDS_45_SPADES,
	CARDS_46_SPADES,
	CARDS_47_SPADES,
	CARDS_48_SPADES,
	CARDS_49_SPADES,
	CARDS_50_SPADES,
	CARDS_51_SPADES,
	CARDS_52_SPADES,
	CARDS_END,
};

class GameTable :
	public Room
{
public:
	int DeckSize; //MAX 52.
	vector<int> Deck;

public:
	GameTable();
	virtual ~GameTable();
};

