#pragma once

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 960

#define BUFSIZE 512
#define SHORT_BUFSIZE 20
#define LONG_BUFSIZE 200

#define FPS 60

#define NOTICE_X 525
#define NOTICE_Y 117

#define GAMESTART_NOTICE_X 476
#define GAMESTART_NOTICE_Y 248

#define GAMEROUND_NOTICE_X 392
#define GAMEROUND_NOTICE_Y 265

#define GAMEROUND_USER_X 462
#define GAMEROUND_FIRST_USER_Y 291
#define GAMEROUND_SECOND_USER_Y 333

#define TIME_NOTICE_X 387
#define TIME_NOTICE_Y 709

#define ANSWER_NOTICE_X 293
#define ANSWER_NOTICE_Y 95
#define ANSWER_NOTICE_STR_X 373
#define ANSWER_NOTICE_STR_Y 105

#define RESULT_NOTICE_X 383
#define RESULT_NOTICE_Y 273

#define RESULT_USER_X 545
#define RESULT_FIRST_USER_Y 295
#define RESULT_SECOND_USER_Y 335

#define LEADERBOARD_NOTICE_X 492
#define LEADERBOARD_NOTICE_Y 185

#define LEADERBOARD_USER_X 576
#define LEADERBOARD_USER_Y 275

enum INPUT_KEY
{
	INPUT_KEY_ENTER,
};